version: '3.8'

services:
  frontend:
    build:
      context: ./earlyspring
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./earlyspring/src:/app/src
      - ./earlyspring/public:/app/public
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - FRONTEND_URL=http://localhost:5173
    external_links:
      - mongodb:mongodb
    restart: unless-stopped