spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: 'alarm-clock-service'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
  data:
    mongodb:
      uri: ${MONGODB_URI}