FROM node:20-alpine

WORKDIR /app

COPY package.json /app
RUN npm install

# Copy application code
COPY . /app

# Set environment variables
ENV NODE_ENV=production

EXPOSE 5173

CMD ["npm", "run", "dev"]